global.CREEP_MODE_UNKNOWN = -1
global.CREEP_MODE_MINE_AS_HARVESTER = 0
global.CREEP_MODE_MINE_WITH_TRANSPORT = 1
global.CREEP_MODE_MINE_WITH_LINK = 2
global.CREEP_MODE_TRANSPORT_STORAGE_TO_TOWER = 3
global.CREEP_MODE_TRANSPORT_STORAGE_TO_SPAWN = 4
global.CREEP_MODE_TRANSPORT_STORAGE_TO_CONTAINERS = 5
global.CREEP_MODE_TRANSPORT_MINER_TO_STORAGE = 6
global.CREEP_MODE_TRANSPORT_LINK_TO_STORAGE = 7

global.MAX_TRANSPORTS_FOR_CONTAINERS = 3
global.MAX_TRANSPORTS_PER_MINER = 2
global.MAX_TRANSPORTS_PER_TOWER = 1
global.MAX_TRANSPORTS_PER_SPAWN = 2
global.MAX_TRANSPORTS_PER_LINK = 1


global.EXTENSION_FIND_RANGE = 20

global.MIN_TOWER_REPAIR_RATIO = 0.50

global.SC_CHRISTOPHER_COLUMBUS = {name: "Christopher Columbus", parts: [MOVE, MOVE, MOVE, MOVE, CLAIM]};