// Task constants
global.TASK_UNDEFINED = -1

global.TASK_NEED_ENERGY = 0
global.TASK_NEED_TRANSPORT = 1
global.TASK_NEED_REPAIR = 2
global.TASK_NEED_ROADS = 3
global.TASK_NEED_UPGRADE = 4
global.TASK_NEED_CREEP = 5
global.TASK_PRIORITY_LOW = 0

global.TASK_PRIORITY_MEDIUM = 1
global.TASK_PRIORITY_HIGH = 2
global.TASK_PRIORITY_HIGHEST = 3

global.TASK_DURATION_LIFETIME = "lifetime"
global.TASK_DURATION_COMPLETION = "completion"

global.TASK_ROAD_HITS_MIN = 0.50
global.TASK_ROAD_HITS_MAX = 1.00
global.TASK_WALL_HITS_MIN = 0.10

global.TASK_NUM_BUILDERS_PER_SITE = 2

global.NO_TASK = 0
global.TASK_IN_PROGRESS = 1
global.TASK_IS_DONE = 2

